### ISSUE TITLE
Can the new version be published to npm?

### ISSUE THREAD

**Issue by EyePulp** [csquared/fernet.js#15]
Hey @csquared, thanks for doing MR #13 -- can you also publish the update to NPM?  I think the package.json is already bumped, so just publishing should be sufficient.

Thanks, and thanks for the node implementation of this. =)

**Comment by csquared** [comment]
Just published!

Thanks and glad it's working for you :)

**Comment by EyePulp** [comment]
Awesome, thanks so much!

- andrew -

On September 28, 2017 at 12:42:59 PM, Chris Continanza (
notifications@github.com) wrote:

Just published!

Thanks and glad it's working for you :)

> On Sep 28, 2017, at 6:59 AM, EyePulp <notifications@github.com> wrote:
>
> Hey @csquared, thanks for doing MR #13 -- can you also publish the update
to NPM? I think the package.json is already bumped, so just publishing
should be sufficient.
>
> Thanks, and thanks for the node implementation of this. =)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/csquared/fernet.js/issues/15#issuecomment-332911252>,
or mute the thread
