### ISSUE TITLE
Vulnerability | Crypto.JS 

### ISSUE THREAD

**Issue by danielsinai** [csquared/fernet.js#29]
Hi 👋 
Would it be possible to upgrade the crypto-js library that is being used in this library?
The current one seems to have a [High-risk vul](https://github.com/brix/crypto-js/security/advisories/GHSA-xwcq-pm8m-c4vf) 

Thanks!

**Comment by kennyp** [comment]
Upgraded in #32 and part of the `0.3.2` release.
